{
 "title": "pgsharding load",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "CPU used by pgbouncer app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(uptycs_app_cpu{app_name=~\".*pgbouncer.*\"}) by (host_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used by pgbouncer app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(uptycs_app_memory{app_name=~\".*pgbouncer.*\"}) by (host_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used by apisever app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(uptycs_app_memory{app_name=\"apiserver\"}) by (host_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU used by apisever app",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(uptycs_app_cpu{app_name=\"apiserver\"}) by (host_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pg nodes memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "((uptycs_memory_used{node_type=\"pg\"}/uptycs_total_memory{node_type=\"pg\"})*100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pg nodes CPU busy %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "100-uptycs_idle_cpu{node_type=\"pg\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}